### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by whiteblXK**
moved 'add offer' to admin panel
removed Homepay service
fixed delivering points in PagSeguro
full twig template support

### CODE REVIEW

**Comment by whiteblXK** [comment]
Yeah, but I will be grateful if someone do more tests cuz I'm still learning :p

**Comment by gabz182** [comment]
> moved 'add offer' to admin panel
> removed Homepay service
> fixed delivering points in PagSeguro
> full twig template support
-----
i can't see add offer in admin panel, lol o.o
how i can configure pagseguro? old version don't works, i want test your update.

**Comment by SlawomirBoczek** [comment]
What did you change to fix PagSeguro? I can't find any changes in code.

**Comment by slawkens** [comment]
What did you change to fix PagSeguro? I can't find any changes in code.

**Comment by gabz182** [comment]
Wasted 3 days, and pagseguro don't work, i'm sad :(
i really need this , but i don't know more how to fix it.

**Comment by whiteblXK** [comment]
> What did you change to fix PagSeguro? I can't find any changes in code.

From apache logs `PHP Fatal error: Class 'GesiorShop' not found in /var/www/html/payments/pagseguro.php on line 57`, so I added `require_once LIBS . 'shop-system.php';` into `payments/pagseguro.php`,

**Comment by whiteblXK** [comment]
> > moved 'add offer' to admin panel
> > removed Homepay service
> > fixed delivering points in PagSeguro
> > full twig template support
> 
> i can't see add offer in admin panel, lol o.o
> Notice: Undefined index: uptimeReadable in C:\xampp\htdocs\admin\template\template.php
> how i can configure pagseguro? old version don't works, i want test your update.

I have installed this plugin many times in clean MyAAC from master, are you sure you have latest `admin\template\template.php`?

**Comment by gabz182** [comment]
> > > moved 'add offer' to admin panel
> > > removed Homepay service
> > > fixed delivering points in PagSeguro
> > > full twig template support
> > 
> > 
> > i can't see add offer in admin panel, lol o.o
> > Notice: Undefined index: uptimeReadable in C:\xampp\htdocs\admin\template\template.php
> > how i can configure pagseguro? old version don't works, i want test your update.
> 
> I have installed this plugin many times on clean MyAAC from master and gifts page works well, are you sure you have latest `admin\template\template.php`?

Yes, reinstall for new installation, but still don't see add offer in panel admin.
i'm using PhP 7 and xampp. can you help me please?
[https://imgur.com/EgieZmZ](url)

**Comment by whiteblXK** [comment]
Can you check your database table `myaac_admin_menu` and check if you have `Gifts` record?

This is my discord: @whiteblXK#9616

**Comment by gabz182** [comment]
it's work now! Thank you bro!

**Pull request merged**
